import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js';
import { getAuth, GoogleAuthProvider, onAuthStateChanged, signInWithEmailAndPassword, signInWithPopup, signOut } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js';
import { getDatabase, ref, get } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-database.js';
import { getFunctions, httpsCallable } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-functions.js';

const firebaseConfig={apiKey:'AIzaSyDPS8qby2nMPc0beclK7igZcD-PvVOjviw',authDomain:'idle-wonders.firebaseapp.com',projectId:'idle-wonders',storageBucket:'idle-wonders.firebasestorage.app',messagingSenderId:'537194194344',appId:'1:537194194344:web:d71107c9a027215e18299d',databaseURL:'https://idle-wonders-default-rtdb.firebaseio.com'};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getDatabase(app),functions=getFunctions(app);
const call=name=>httpsCallable(functions,name);
const api={getSystem:call('adminGetSystem'),setSystem:call('adminSetSystem'),search:call('adminSearchAccounts'),getAccount:call('adminGetAccount'),updateAccount:call('adminUpdateAccount'),setItem:call('adminSetInventoryItem'),status:call('adminSetAccountStatus'),revoke:call('adminRevokeSessions'),remove:call('adminDeleteAccount'),audit:call('adminListAudit'),getMap:call('adminGetMap'),saveMap:call('adminSaveMapDraft'),publishMap:call('adminPublishMap'),rollbackMap:call('adminRollbackMap')};
const $=id=>document.getElementById(id); let selectedUid=null;
function toast(message,error=false){const el=$('toast');el.textContent=message;el.style.borderColor=error?'#b35d57':'#6e8a66';el.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.hidden=true,3500)}
function err(e){console.error(e);toast(e?.message||'Action failed.',true)}
async function invoke(fn,data={}){const result=await fn(data);return result.data}

document.querySelectorAll('[data-tab]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b===button));document.querySelectorAll('[data-panel]').forEach(p=>p.classList.toggle('active',p.dataset.panel===button.dataset.tab));if(button.dataset.tab==='players')loadPlayers();if(button.dataset.tab==='audit')loadAudit();}));
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginMessage').textContent='Signing in…';try{await signInWithEmailAndPassword(auth,$('email').value.trim(),$('password').value)}catch(error){$('loginMessage').textContent=error.message}});
$('googleLogin').onclick=()=>signInWithPopup(auth,new GoogleAuthProvider()).catch(e=>$('loginMessage').textContent=e.message);
$('signOutButton').onclick=()=>signOut(auth);
onAuthStateChanged(auth,async user=>{if(!user){$('loginView').hidden=false;$('adminView').hidden=true;return}const token=await user.getIdTokenResult(true);if(token.claims.admin!==true){$('loginMessage').textContent='This account is not an administrator.';await signOut(auth);return}$('adminIdentity').textContent=user.email||user.uid;$('loginView').hidden=true;$('adminView').hidden=false;loadSystem();});

async function loadSystem(){try{const c=await invoke(api.getSystem);$('maintenanceMode').checked=!!c.maintenanceMode;$('minimumVersion').value=c.minimumVersion||'';$('systemMessage').value=c.message||'';$('systemRevision').value=c.revision||1;$('shutdownAt').value=c.shutdownAt?new Date(c.shutdownAt).toISOString().slice(0,16):'';$('systemState').textContent=c.maintenanceMode?'Maintenance active':'Game open'}catch(e){err(e)}}
$('saveSystem').onclick=async()=>{try{await invoke(api.setSystem,{maintenanceMode:$('maintenanceMode').checked,minimumVersion:$('minimumVersion').value.trim(),message:$('systemMessage').value.trim(),shutdownAt:$('shutdownAt').value?new Date($('shutdownAt').value).toISOString():null,revision:Number($('systemRevision').value)||1,reason:'Published from admin dashboard'});toast('System settings published.');loadSystem()}catch(e){err(e)}};
$('clearShutdown').onclick=()=>{$('shutdownAt').value=''};
async function loadPlayers(){try{const snap=await get(ref(db,'worlds/family-world/players'));const players=Object.values(snap.val()||{});$('onlinePlayers').innerHTML=players.length?players.map(p=>`<article class="player-card"><div><strong>${escapeHtml(p.name||'Wanderer')}</strong><small>${escapeHtml(p.area||'Unknown')} · ${Math.round(p.x||0)}, ${Math.round(p.y||0)}</small><small>Combat ${p.combatLevel||1} · ${escapeHtml(p.activity||'Exploring')}</small></div><span class="status">Online</span></article>`).join(''):'<p class="hint">Nobody is currently connected.</p>'}catch(e){err(e)}}
$('refreshPlayers').onclick=loadPlayers;
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
$('searchAccounts').onclick=async()=>{try{const rows=await invoke(api.search,{query:$('accountSearch').value.trim()});$('accountResults').innerHTML=rows.map(r=>`<button class="result-card" data-uid="${r.uid}"><span><strong>${escapeHtml(r.displayName||'Unnamed')}</strong><small>${escapeHtml(r.email||'No email')} · ${r.uid}</small></span><span class="status">${r.banned?'Banned':r.suspended?'Suspended':'Open'}</span></button>`).join('')||'<p class="hint">No matching accounts.</p>';document.querySelectorAll('[data-uid]').forEach(b=>b.onclick=()=>openAccount(b.dataset.uid))}catch(e){err(e)}};
async function openAccount(uid){try{selectedUid=uid;const a=await invoke(api.getAccount,{uid});$('accountEditor').hidden=false;$('editorName').textContent=a.user.displayName||a.user.email||'Unnamed';$('editorUid').textContent=uid;$('editDisplayName').value=a.user.displayName||'';$('editCoins').value=a.save.inventory?.coins||0;$('editGameVersion').value=a.profile.gameVersion||'';$('editX').value=a.save.player?.x??1900;$('editY').value=a.save.player?.y??2320;$('editSuspended').checked=!!a.profile.suspended;$('editBanned').checked=!!a.profile.banned;$('rawSave').textContent=JSON.stringify(a.save,null,2)}catch(e){err(e)}}
$('reloadAccount').onclick=()=>selectedUid&&openAccount(selectedUid);
$('saveAccount').onclick=async()=>{if(!selectedUid)return;try{await invoke(api.updateAccount,{uid:selectedUid,displayName:$('editDisplayName').value.trim(),coins:Number($('editCoins').value),x:Number($('editX').value),y:Number($('editY').value),reason:$('editReason').value.trim()});await invoke(api.status,{uid:selectedUid,suspended:$('editSuspended').checked,banned:$('editBanned').checked,reason:$('editReason').value.trim()});toast('Account updated.');openAccount(selectedUid)}catch(e){err(e)}};
$('setItem').onclick=async()=>{if(!selectedUid)return;try{await invoke(api.setItem,{uid:selectedUid,itemKey:$('editItemKey').value.trim(),quantity:Number($('editItemQuantity').value),reason:$('editReason').value.trim()});toast('Inventory updated.');openAccount(selectedUid)}catch(e){err(e)}};
$('moveStart').onclick=async()=>{if(!selectedUid)return;try{await invoke(api.updateAccount,{uid:selectedUid,x:1900,y:2320,reason:$('editReason').value.trim()||'Moved to Starting Town'});toast('Player moved to Starting Town.');openAccount(selectedUid)}catch(e){err(e)}};
$('revokeSessions').onclick=async()=>{if(!selectedUid||!confirm('Revoke every active session for this account?'))return;try{await invoke(api.revoke,{uid:selectedUid,reason:$('editReason').value.trim()});toast('Sessions revoked.')}catch(e){err(e)}};
$('deleteAccount').onclick=async()=>{if(!selectedUid||prompt('Type DELETE to permanently remove this account and save data.')!=='DELETE')return;try{await invoke(api.remove,{uid:selectedUid,reason:$('editReason').value.trim()});toast('Account deleted.');$('accountEditor').hidden=true;selectedUid=null}catch(e){err(e)}};
async function loadAudit(){try{const rows=await invoke(api.audit,{limit:100});$('auditLog').innerHTML=rows.map(a=>`<article class="audit-entry"><strong>${escapeHtml(a.action)}</strong> <small>${new Date(a.at).toLocaleString()}</small><div>${escapeHtml(a.adminEmail||a.adminUid)} → ${escapeHtml(a.targetUid||'system')}</div>${a.reason?`<small>${escapeHtml(a.reason)}</small>`:''}</article>`).join('')||'<p class="hint">No admin actions recorded.</p>'}catch(e){err(e)}}
$('refreshAudit').onclick=loadAudit;
async function loadMap(){try{const m=await invoke(api.getMap);$('mapJson').value=JSON.stringify(m.draft||{version:1,biomes:[],towns:[],resources:[],enemies:[],fishingSpots:[]},null,2);$('mapStatus').textContent=`Published r${m.publishedRevision||0}`;}catch(e){err(e)}}
$('loadMap').onclick=loadMap;
$('saveMap').onclick=async()=>{try{await invoke(api.saveMap,{map:JSON.parse($('mapJson').value),note:$('mapNote').value.trim()});toast('Map draft saved.')}catch(e){err(e)}};
$('publishMap').onclick=async()=>{if(!confirm('Publish this map JSON as a new revision?'))return;try{await invoke(api.publishMap,{map:JSON.parse($('mapJson').value),note:$('mapNote').value.trim()});toast('Map revision published.');loadMap()}catch(e){err(e)}};
$('rollbackMap').onclick=async()=>{if(!confirm('Rollback to the preceding published map revision?'))return;try{await invoke(api.rollbackMap,{note:$('mapNote').value.trim()});toast('Map rolled back.');loadMap()}catch(e){err(e)}};
